[env:rp2040_zero]
# Switch to the platform wrapper that fully supports the Philhower core
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = pico
framework = arduino
board_build.core = earlephilhower
monitor_speed = 115200
lib_deps = 
    adafruit/Adafruit TinyUSB Library
build_flags = 
    -D USE_TINYUSB